baseURL = "/"
languageCode = "en-us"
title = "Always Carry A Book!"
ignoreErrors = ["error-remote-getjson"]

[permalinks]
	books = "/:filename/"

[params]
	homeText = "Life is lighter when you have one on you"
	search = "true"

[menu]
	[[menu.main]]
	name = "Home"
	url = "/"
	weight = 1
	[[menu.main]]


